---
services:
  db:
    image: redis:latest
    container_name: redis
    volumes:
      - db_data:/data
    command: >
      redis-server --appendonly yes --appendfsync always
    ports:
      - "6379:6379"

  quote-consumer:
    build:
      context: .
    command: quote-consumer
    ports:
      - "8000:8000"
    environment:
      EXCHANGE_API_URL: "${EXCHANGE_API_URL}"
      EXCHANGE_FETCH_INTERVAL: "${EXCHANGE_FETCH_INTERVAL}"
      QUOTE_CONSUMER_HOST: "${QUOTE_CONSUMER_HOST}"
      QUOTE_CONSUMER_PORT: "${QUOTE_CONSUMER_PORT}"
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      CURRENCY_PAIR_TTL: "${CURRENCY_PAIR_TTL}"
    depends_on:
      - db

  currency-conversion-api:
    build:
      context: .
    command: api
    ports:
      - "8001:8001"
    environment:
      CURRENCY_CONVERSION_API_HOST: "${CURRENCY_CONVERSION_API_HOST}"
      CURRENCY_CONVERSION_API_PORT: "${CURRENCY_CONVERSION_API_PORT}"
      MAX_QUOTE_AGE: "${MAX_QUOTE_AGE}"
      QUOTE_CONSUMER_API_URL: "${QUOTE_CONSUMER_API_URL}"

volumes:
  db_data:
